version: 2

sources:
  - name: olist
    database: olist-e-commerce-analysis
    schema: olist_raw
    tables:
      - name: customers
      - name: geolocs
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: orders
      - name: product_category_names
      - name: products
      - name: sellers